// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFd9Vf0n2-oOQAI3pf_yBeBd1i_ySClzI',
    appId: '1:763643886491:android:e275f82b8db451d67bff3e',
    messagingSenderId: '763643886491',
    projectId: 'luno-quit-smoking-app',
    storageBucket: 'luno-quit-smoking-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoJmRnAj5tqz7wKy1stwnpgRsDV9FC2l8',
    appId: '1:763643886491:ios:79f6d2e9395e6b077bff3e',
    messagingSenderId: '763643886491',
    projectId: 'luno-quit-smoking-app',
    storageBucket: 'luno-quit-smoking-app.firebasestorage.app',
    androidClientId:
        '763643886491-an75feffflt5vmi6i511tg6rkp544s0k.apps.googleusercontent.com',
    iosClientId:
        '763643886491-cr8214f4enrgugdn4cu6ur70hrlbumoj.apps.googleusercontent.com',
    iosBundleId: 'com.dogualagoz.cigerito',
  );
}
